# Random Numbers in numpy

***

In [1]:
# Numerical arrays, random numbers.
import numpy as np

# Plots.
import matplotlib.pyplot as plt

## Python Standard Library

https://docs.python.org/3/library/random.html

***

In [2]:
# The random module from the standard library.
import random

In [3]:
# Using autocomplete, we can a get a flavour of the module.
# Putting a question mark in front of a function name prints
# a little help message.
?random.randint

Signature: random.randint(a, b)
Docstring:
Return random integer in range [a, b], including both end points.
        
File:      c:\users\conor\anaconda3\lib\random.py
Type:      method

In [4]:
# Based on the above, we can generate a random integer between
# 10 and 20, inclusive .
random.randint(10, 20)

10

In [5]:
# Generate a list of 100 random integers between 1 and 10.
L = [random.randint(1, 10) for i in range(100)]

# Show the first ten items of L.
L[:10]

[2, 4, 4, 5, 2, 10, 8, 4, 10, 4]

In [6]:
# can also use random.seed to set 1st number the same for list to use later

In [7]:
# List of car makes.
# lists are sequences.
makes = ['Toyota', 'Skoda', 'Ford', 'Renault']

In [8]:
# Select one at random.
random.choice(makes)

'Toyota'

In [9]:
# Select ten random makes (with replacement).
random.choices(makes, k=10)

['Ford',
 'Renault',
 'Skoda',
 'Ford',
 'Renault',
 'Ford',
 'Ford',
 'Skoda',
 'Toyota',
 'Ford']

In [10]:
# First eight letters.
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [11]:
# Shuffle them.
random.shuffle(letters)

In [12]:
# Look at letters after shuffle.
letters

['H', 'B', 'F', 'A', 'G', 'D', 'E', 'C']

In [13]:
# Random selection without replacement.
random.sample(letters, k=5)

['H', 'D', 'B', 'F', 'E']

In [14]:
# Random real (floating-point) number. [0.0, 1.0)
random.random()

0.7521912531579201

In [15]:
# Pick a random floating point number between 0.0 and 100.0. [0.0, 100.0]
# endpoints are included
random.uniform(0.0, 100.0)

17.22040506223943

## numpy

[numpy API Reference: Random sampling](https://numpy.org/doc/stable/reference/random/index.html)

https://numpy.org/doc/stable/reference/random/index.html

***

In [16]:
# Random Number Generator (RNG) for generating random numbers.
rng = np.random.default_rng()

In [17]:
rng.random()

0.7516985565811737

In [18]:
# Generate 10 random floating point numbers in the interval 0.0 [included] to 1.0 (excluded).
rng.random(10)

array([0.63006627, 0.62730159, 0.25208455, 0.52288596, 0.6051842 ,
       0.91994184, 0.80814404, 0.30819682, 0.72587205, 0.63970458])

Generate numbers on a standard Normal distribution.
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.standard_normal.html#numpy.random.Generator.standard_normal

The mean is 0.0 and standard deviation is 1.0.

The numbers generated should be, on average, centred on 0.0.

More than 99% of the numbers generated should be in the interval (-3.0, 3.0).

https://www.scribbr.com/statistics/standard-normal-distribution/

In [19]:
# Generate numbers on a standard Normal distribution.
rng.standard_normal(10)

array([ 0.49424661, -1.09061664, -0.41355829, -0.27988189,  0.27395307,
       -1.26923764,  2.09831035, -1.2666004 , -0.19086455, -0.70820919])

In [20]:
# Generated 15 integers between 10 [included] and 20 (excluded).
rng.integers(low=10, high=20, size=15) 

array([16, 13, 10, 14, 12, 17, 19, 14, 10, 16, 15, 13, 10, 18, 17],
      dtype=int64)

## Plotting Bar Charts/ Plotting Ditributions

***

In [21]:
# The lowest integer allowed.
low = 1

# The highest integer allowed.
high = 10

# The number of integers to generate.
size = 100000

In [25]:
# Generate a list of random integers.
rand_ints = rng.integers(low=1, high=11 + 1, size=100)

# Show.
rand_ints

array([ 5,  5,  7,  4,  9,  8, 11,  2, 10,  6,  3,  9, 11,  1,  7,  4,  9,
        1,  5,  4, 11,  5,  5, 10, 10,  1, 10,  1,  1,  5, 11,  9,  3,  3,
        9,  1,  4, 10,  9,  3,  9,  6, 11,  7,  1,  2,  7,  7,  1,  1,  9,
        9,  7,  3,  5,  9,  6,  9,  7,  1,  6,  7,  3,  2,  8,  1,  6,  2,
        6,  5, 11,  4,  7,  7,  3,  5, 10,  6,  2,  9,  5, 10, 11,  7,  9,
        1,  4, 11, 11,  3,  5,  6,  8,  9, 10,  6,  3,  6, 11,  1],
      dtype=int64)

In [23]:
# The unique elements of rand_ints.
np.unique(rand_ints)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)